### ISSUE TITLE
Convert source code to ES6

### ISSUE THREAD

**Issue by noyesa** [noyesa/broccoli-global-exporter#10]

**Comment by noyesa** [comment]
Fixed by #11

**Comment by amercier** [comment]
I think there's one line missing line at [index.js#L4](https://github.com/noyesa/broccoli-global-exporter/blob/master/src/index.js#L4):

```
module.exports = exportGlobals;
```

Shouldn't this be the following, instead?

```
export default exportGlobals;
```

**Comment by noyesa** [comment]
This was to maintain backward compatibility after the upgrade to Babel 6.x. The old CJS module transformer would set `module.exports` to equal your default export as long as there are no other, named exports. This meant you could import this in your Brocfile using `var exportGlobals = require('broccoli-global-exporter');`.

With Babel 6, the default export is _always_ exported as a named property `default`, meaning this would have to change to `var exportGlobals = require('broccoli-global-exporter').default;` which isn't backward compatible.
